### ISSUE TITLE
Firefox release

### ISSUE THREAD

**Issue by pechy** [khloke/play-to-xbmc-chrome#107]
Hi,
I really like this plugin, I'm testing it now and it seems to work fine in Firefox (Firefox 50.0.1). It's much better then older Send to XBMC! Thank you!

My question is whether you're planning to add this it to AMO, the standard Firefox add-on repository (if you haven't done that yet, but I haven't found it).
Right now, I had to install it through about:debugging and Load Temporary Plugin there, which is not really convenient way, because the add-on stays there only until restart of Firefox.

I'm not really an expert in Firefox extensions, but I guess that it shouldn't be that complicated, since I was able to install it without any problems in debug mode...

Thanks

**Comment by maciex** [comment]
Hi @pechy 
As of today you could use one of the releases of this add-on in my forked repository: https://github.com/maciex/play-to-kodi/releases

There's already a signed add-on there, not yet published on the AMO site.
If you test it a little please let me know if it works OK for you.
I'll upload it to AMO in the future.

**Comment by khloke** [comment]
Hi @maciex 

I really appreciate that you're doing this. Due to other commitments it's now very difficult for me to keep maintaining the Chrome version, let alone another Firefox one. It's great that you've decided to fork it and release it.

For everyone who is here looking for the Firefox version, please visit @maciex's releases (https://github.com/maciex/play-to-kodi/releases).

Cheers,
KH
