### ISSUE TITLE
Could not determine what to do with link: tel:01234 567890

### ISSUE THREAD

**Issue by LoueeD** [khloke/play-to-xbmc-chrome#119]
Your code simply need to include the telephone link "tel:[number]"
`
if (!linkUrl || linkUrl.trim() == ''
        || (linkUrl && (linkUrl.indexOf('#') == 0
        || linkUrl.indexOf('mailto') == 0
        || linkUrl.indexOf('javascript') == 0
        || linkUrl.indexOf('irc') == 0))) {
        //Do nothing to these links.
    } else {
        console.log("Could not determine what to do with link: " + linkUrl);
    }
`

**Comment by jnwatts** [comment]
Actually, I would suggest they DON'T log links the script doesn't recognize. I just had to uninstall the extension because every time I mouse over a JS-generated link that downloads a ~8k file I get a console.log() with the entire 8k URL. The logic here should look for what is needs, and IGNORE it otherwise in the else case.
