### ISSUE TITLE
Sending Yle Areena videos to Kodi does not work anymore

### ISSUE THREAD

**Issue by amergin** [khloke/play-to-xbmc-chrome#64]
It is no longer possible to send Yle Areena videos to Kodi. I remember this addon used to work with the site and probably stopped working around the time Yle updated their website.

Example:  Go to http://areena.yle.fi/1-2354823 -> **Play now** and the other buttons are greyed out.

**Comment by khloke** [comment]
I would really like to make this work but unfortunately I could not access any of the videos since I'm not in Finland and I don't have any VPN servers there either. It would be great is @josutus would pick this up, since he added the support for these services, but I wouldn't bet on it considering he doesn't work on any other projects on Github. Sorry.
